apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  type: NodePort
  selector:
    app: trivial-go-web-app
  ports:
      - nodePort: 31000
        protocol: TCP
        port: 8080
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Priv
